CREATE DATABASE HOSPITAL;
USE HOSPITAL;

CREATE TABLE PATIENT(
	PATIENT_ID INT,
	PATIENT_NAME VARCHAR(20),
	PATIENT_AGE INT,
	PATIENT_GENDER VARCHAR(1),
	PATIENT_ADDRESS VARCHAR(20),
	PATIENT_DISEASE VARCHAR(20),
	DOCTOR_ID INT,
    PRIMARY KEY(PATIENT_ID)
);

CREATE TABLE DOCTOR(
	DOCTOR_ID INT,
	DOC_NAME VARCHAR(20),
	DOC_AGE INT,
	GENDER VARCHAR(1),
	ADDRESS VARCHAR(20),
    PRIMARY KEY(DOCTOR_ID)
);

ALTER TABLE PATIENT
ADD FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID);

CREATE TABLE LAB(
	LAB_NO VARCHAR(10),
	PATIENT_ID INT,
	DOCTOR_ID INT,
	DATE DATE,
	AMOUNT INT,
    PRIMARY KEY(LAB_NO),
    FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID),
    FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);

CREATE TABLE INPATIENT(
	PATIENT_ID INT,
	ROOM_NO INT,
	DATE_OF_ADM DATE,
	DATE_OF_DIS DATE,
	LAB_NO varchar(10),
    PRIMARY KEY(PATIENT_ID),
    FOREIGN KEY (ROOM_NO) REFERENCES ROOM(ROOM_NO),
    FOREIGN KEY(LAB_NO) REFERENCES LAB(LAB_NO)
);

CREATE TABLE OUTPATIENT(
	PATIENT_ID INT,
	DATE DATE,
	LAB_NO VARCHAR(10),
    PRIMARY KEY(PATIENT_ID),
    FOREIGN KEY(LAB_NO) REFERENCES LAB(LAB_NO)
);

CREATE TABLE ROOM(
	ROOM_NO INT,
	ROOM_TYPE VARCHAR(10),
	STATUS VARCHAR(10),
    PRIMARY KEY(ROOM_NO)
);

CREATE TABLE BILL(
	BILL_NO INT,
	PATIENT_ID INT ,
	DOCTOR_CHARGE INT,
	ROOM_CHARGE INT,
	NO_OF_DAYS INT,
	LAB_CHARGE INT,
	BILL INT,
	PRIMARY KEY(BILL_NO),
	FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);

